services:
  api:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      JWT_SECRET: "${JWT_SECRET}"

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
    volumes:
      - db-volume:/var/lib/mysql

volumes:
  db-volume: {}
